---
- name: Build, tag, and push Docker image
  hosts: docker_hosts
  become: true
  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        name: igpabctech # Name of the image
        source: build
        tag: latest   # Tag for the image
        build:
          path: .  # Path to the directory containing Dockerfile
        push: false  # Set to true if you want to push immediately after building

    - name: Tag Docker image
      community.docker.docker_image:
        name: igpabctech:latest  # Source image
        source: local
        repository: ashjo317/igp-devops  # Target repository (Docker Hub or private registry)
        tag: latest  # New tag to apply

    - name: Push Docker image to registry
      community.docker.docker_image:
        name: ashjo317/igp-devops:latest  # Full name of the image to push
        source: push
        push: true  # Push the image to the repository
