kind: Deployment
apiVersion: apps/v1
metadata:
    name: igpabctechkube
spec:
    replicas: 2
    minReadySeconds: 45
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
    selector:
        matchLabels:
            app: igpabctechkube
    template:
        metadata:
            labels:
                app: igpabctechkube
        spec:
            containers:
                - image: ashjo317/igp-devops:latest
                  name: igpabctechkube
---

kind: Service
apiVersion: v1
metadata:
    name: igpabctechkube-service
spec:
    type: NodePort
    selector:
        app: igpabctechkube
    ports:
        - port: 80 #cluster port
          targetPort: 8080 #container image port
