---
- name: Deploy Application on Kubernetes Cluster
  hosts: kubernetes_hosts
  become: true
  tasks:
    - name: List files in the directory where the playbook is running
      command: ls
      register: dir_contents

    - name: Display directory contents
      debug:
        var: dir_contents.stdout_lines
    
    - name: Deploy application - Deployment
      command: kubectl apply --kubeconfig "/home/ubuntu/.kube/config" -f "/var/lib/jenkins/workspace/ci-cd-igp-pipeline-with-ansible/ABC Technologies/k8deployment.yaml" --validate=false
      register: deployment_result

    - name: Display Deployment Result
      debug:
        var: deployment_result.stdout
