- name: Deploy Application on Kubernetes Cluster
  hosts: kubernetes_hosts
  become: true
  tasks:
    - name: Deploy application - Deployment
      command: kubectl apply -f k8deployment.yaml
      register: deployment_result

    - name: Display Deployment Result
      debug:
        var: deployment_result.stdout
