---
- name: Manage Kubernetes deployments
  hosts: localhost
  gather_facts: yes
  vars:
     kubeconfig_file: '~/.kube/config'
  tasks:
    - name: Create a namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_file }}"
        name: jenkinskube
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploy an application
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig_file }}"
        namespace: jenkinskube
        state: present
        src: k8deployment.yaml
