---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: igpabctechnologiesapp
  name: igpabctechnologiesapp
  namespace: default
spec:
  containers:
  - image: ashjo317/igp-devops
    name: igpabctechnologiesapp
    ports:
        - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
