apiVersion: v1
kind: Service
metadata:
  name: igpabctechnologiesapp-service
  labels:
    app: igpabctechnologiesapp
spec:
  type: NodePort
  selector:
    run: igpabctechnologiesapp  # This should match the pod's label
  ports:
    - port: 8080                 # The port that will be exposed by the service
      targetPort: 8080           # The port on the pod that the service will forward traffic to
      nodePort: 30001            # The port on each node that will forward to the service (optional)
